run_name: null
device: auto
seed: 67

model:
  model_channels: 128
  channel_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.1
  resamp_with_conv: true

diffusion:
  T: 1000
  beta_start: 0.0001
  beta_end: 0.02

train:
  num_epochs: 5
  batch_size: 128
  test_batch_size: 256
  learning_rate: 0.0001
  checkpoint_every: 1
