run_name: null
device: auto
seed: 42

model:
  model_channels: 64
  channel_mult: [1, 2, 4]
  num_res_blocks: 2
  attn_resolutions: [7]
  dropout: 0.0
  resamp_with_conv: true

diffusion:
  T: 200
  beta_start: 0.0001
  beta_end: 0.02

train:
  num_epochs: 2000
  batch_size: 64
  test_batch_size: 1000
  learning_rate: 0.0001
  checkpoint_every: 500
